version: '3'

services:

  diplom:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"